---
version: "3.9"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    hostname: wireguard
    ports:
      - 51820:51820/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Indiana/Indianapolis
      - SERVERURL=${SERVERURL}
      - SERVERPORT=${SERVERPORT}
      - PEERS=${PEERS}
      - PEERDNS=${PEERDNS}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}
      - ALLOWEDIPS=${ALLOWEDIPS}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /lib/modules:/lib/modules
      - ./config:/config
    networks:
      - wireguard
    restart: unless-stopped
networks:
  wireguard:
    name: wireguard
    ipam:
      config:
        - subnet: "172.16.4.0/24"
          gateway: "172.16.4.1"
